### ISSUE TITLE
code and dataset

### ISSUE THREAD

**Issue by Colin-Jay** [ChaoNyu/CSTShift#1]
Hello! There seems to be a problem in your code or configuration file that is not working properly. Could you check again? In addition, since your experiments can not be replicated, can you publish your predictions for NMRSHIFTDB2-DFT? Thanks!

**Comment by ChaoNyu** [comment]
Thanks for your interest. Can you provide more details about the code problem? E.g. the error message and the related lines

**Comment by Colin-Jay** [comment]
for environment:
miss tensorBoard 
for code: 
[src/utils/nmr_dataset.py](https://github.com/ChaoNyu/CSTShift/blob/c65d83a5b55bb3b0af0bcb7567a41da76e16be0c/src/utils/nmr_dataset.py#L20)
.key maybe is .key()
I have tried to correct the above problem. Then, still failed.

**Comment by Colin-Jay** [comment]
I have downloaded your weights and modified some code to fix the errors, as well as updated the paths in the configuration file. However, I still cannot run it successfully. How can I obtain the results you reported in your paper for the nmrshiftdb2-DFT dataset (both 5 models)? Can you provide a test (or training) configuration file for this dataset? And, could you provide your original prediction results? Thanks!
python src/test.py --test_config configs/embC_test_cheshire.yaml（run failed）

**Comment by ChaoNyu** [comment]
I've reproduced your issue and this is a package problem. A newer version of PyTorch-geometric will be downloaded using `conda install pyg` directly, which is not compatible with the current code. `pip install torch_geometric==2.1.0.post1 torch-sparse==0.6.15 torch-cluster==1.6.1 torch-scatter==2.0.9` should provide a compatible environment to run the code. I've also provided an additional config file `embC_test_nmrshiftdb2_dft.yaml` to test the model on NMRShiftDB2-DFT dataset. The prediction results are stored in the loss_test.pt as the output file. You can also modify the config file to get your customized training/test procedure. Please let me know if you have following questions.

**Comment by Colin-Jay** [comment]
Thank you for your reply! I will try again with your updated environment/configuration file. And can you provide your previous prediction results?

**Comment by ChaoNyu** [comment]
I just added the example test result folder, and you can access the prediction results in the `loss_test.pt` via torch. You can try to modify the config file and run the test.py if you have other requirement for testing.

**Comment by Colin-Jay** [comment]
Can you provide the results of the corresponding H as well? Thank you.

**Comment by Colin-Jay** [comment]
![2](https://github.com/ChaoNyu/CSTShift/assets/40904687/c4dae88f-cd9a-454d-a4f7-992e08894321)
![3](https://github.com/ChaoNyu/CSTShift/assets/40904687/057cf8a5-d39b-48e5-81b5-4066091aab81)

Hi, when I try your newly provided code it still doesn't run successfully. There is no output, the GPU is not being utilized, and the log file does not continue to update.

**Comment by Colin-Jay** [comment]
thanks! I have solved the environment problem and got consistent results

**Comment by ChaoNyu** [comment]
The H example results are provided in the similar way as C now.
